name = "newsroom"
license = "MIT"
licenselink = ""
description = "A simple open source theme for publishing multi-purpose content"
homepage = ""
tags = ["blog", "simple", "dark", "minimalist", "fast", "disqus", "syntax highlighting"]
features = ["blog", "simple", "dark", "minimalist", "fast", "disqus", "syntax highlighting"]
min_version = 0.42

[author]
    name ="weru"
    homepage = ""
